# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G

mod_id=bedrockminer
mod_wrapper_id=bedrockminer-wrapper
mod_name=Bedrock Miner
mod_version=1.6
mod_maven_group=com.github.bunnyi116.blockminer
mod_archives_base_name=bedrock-miner
mod_description=Client mod to mine bedrock!
mod_homepage=https://github.com/bunnyi116/fabric-bedrock-miner
mod_sources=https://github.com/bunnyi116/fabric-bedrock-miner
mod_license=AGPL-3.0

# Fabric Basic Properties
# https://fabricmc.net/versions.html
loader_version=0.19.3

lombok_version=1.18.46