minecraft_version=26.1
minecraft_dependency=>=26.1 <=26.1.2

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=26.1\n26.1.1\n26.1.2

# https://www.fabricmc.net/develop/
fabric_api_version=0.145.1+26.1

# https://modrinth.com/mod/modmenu/versions?g=26.1&l=fabric
modmenu=18.0.0

# https://modrinth.com/mod/cloth-config/versions?g=26.1&l=fabric
cloth-config=26.1.154+fabric