minecraft_version=26.2
minecraft_dependency=>=26.2

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=26.2

# https://www.fabricmc.net/develop/
fabric_api_version=0.152.2+26.2

# https://modrinth.com/mod/modmenu/versions?g=26.2&l=fabric
modmenu=20.0.1

# https://modrinth.com/mod/cloth-config/versions?g=26.2&l=fabric
cloth-config=26.2.155+fabric