minecraft_version=1.19.1
minecraft_dependency=1.19.1

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=1.19.1

# https://www.fabricmc.net/develop/
fabric_api_version=0.58.5+1.19.1


# https://modrinth.com/mod/modmenu/versions?g=1.19.1&l=fabric
modmenu=4.0.5

# https://modrinth.com/mod/cloth-config/versions?g=1.19.1&l=fabric
cloth-config=8.3.134+fabric
