minecraft_version=1.21.9
minecraft_dependency=1.21.9

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=1.21.9

# https://www.fabricmc.net/develop/
fabric_api_version=0.134.0+1.21.9

# https://modrinth.com/mod/modmenu/versions?g=1.21.9&l=fabric
modmenu=16.0.1

# https://modrinth.com/mod/cloth-config/versions?g=1.21.9&l=fabric
cloth-config=20.0.149+fabric